# Generated by Django 5.1.7 on 2025-03-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField()),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
    ]
