# Generated by Django 5.1.7 on 2025-03-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
