# Generated by Django 5.1.7 on 2025-03-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapp', '0002_alter_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to=''),
        ),
    ]
